### ISSUE TITLE
Jobs and transactional integrity docs don't seem to be what actually happens in Solid Queue when using a single DB

### ISSUE THREAD

**Issue by leondmello** [rails/solid_queue#421] opened 2024-11-20 20:01 UTC
> Having your jobs in the same ACID-compliant database as your application data enables a powerful yet sharp tool: taking advantage of transactional integrity to ensure some action in your app is not committed unless your job is also committed and viceversa, and ensuring that your job won't be enqueued until the transaction within which you're enqueuing it is committed.

The above text seems to indicate that if you use the same DB for `ActiveRecord` application models and the Solid Queue models, job enqueuing will only happen if the application model changes are successfully committed to the DB & vice versa.
We changed our implementation to move from a separate DB to a single DB to avail of this. But in practice, we are seeing that this is not the case.

After we installed some debuggers, we found that eventually, [this line of code is hit](https://github.com/rails/solid_queue/blob/393e3b9eff7210f42a43d7e6456b7a172ba78d42/app/models/solid_queue/job/executable.rb#L104). 
[That rails method](https://github.com/rails/rails/blob/7750d64a65e5b2641d87ef45e6e65ace193d9a27/activerecord/lib/active_record/relation.rb#L283) creates a new nested transaction.

Such nested transactions will not roll back all transactions correctly [when using something like postgres](https://github.com/rails/rails/blob/7750d64a65e5b2641d87ef45e6e65ace193d9a27/activerecord/lib/active_record/transactions.rb#L135-L174). We confirmed this behaviour by explicitly rolling back the application transaction after enqueuing the job. The Job record was saved, the application model record was not.

**Comment by leondmello** [comment] 2024-11-20 20:02
An extension to this issue: https://github.com/rails/solid_queue/issues/409

**Comment by rosa** [comment] 2024-11-21 23:28
Hey @leondmello, sorry for the delay, I'm on-call this week. 

> But in practice, we are seeing that this is not the case.

Do you have a minimal reproduction for this where you're seeing this is not the case due to the nested transactions? 

> Maybe a simple fix is to split that up into a `find` & `create!`

Unfortunately, that's not the same as `create_or_find_by!`, as the `find` might return a stale read and then the `create!` fails with a duplicate key exception.

**Comment by rosa** [comment] 2024-11-21 23:31
> An extension to this issue: https://github.com/rails/solid_queue/issues/409

Hmm... I'm not sure how it's an extension 🤔  That other issue is about waiting until all transactions have been committed to actually enqueue the jobs, even if you called `Job.perform_later` inside a transaction. It's done by Active Job, and the default behaviour with respect to that, and how to configure it changed from Rails 7.2 to Rails 8, and the README was outdated.

**Comment by leondmello** [comment] 2024-11-22 15:05
Sorry, used the wrong word.
What I meant was the other issue is related, since the PR associated with that issue updates the transaction section documentation. If the nested transaction issue cannot be fixed, that documentation needs to be updated.
I will create a reproduction repository.

**Comment by onumossn** [comment] 2024-11-22 15:20
I don't think the duplicate key exception can occur in this case at least for postgres since the primary key is auto-incrementing and based on [this](https://www.postgresql.org/docs/current/functions-sequence.html) a duplicate key should not occur and the job_id I think is using `SecureRandom.uuid` which should be extremely unlikely to conflict.

**Comment by rosa** [comment] 2024-11-22 15:31
> the `job_id` I think is using SecureRandom.uuid which should be extremely unlikely to conflict.

The `job_id` there is not Active Job's job ID, it's Solid Queue's internal `solid_queue_jobs.id`.

**Comment by onumossn** [comment] 2024-11-22 15:55
Oh but thats an auto-incrementing id from another table, so it shouldn't be possible for multiple instances connected to the same db to be able to have a conflict.

**Comment by rosa** [comment] 2024-11-22 15:58
> Oh but thats an auto-incrementing id from another table, so it shouldn't be possible for multiple instances connected to the same db to be able to have a conflict.

It shouldn't be possible to conflict on the `solid_queue_jobs.id` key in the `solid_queue_jobs` table on `INSERT` there, but this is a different table. Nothing prevents two concurrent `INSERT` queries to `solid_queue_ready_executions` with the same `job_id` to happen.

**Comment by onumossn** [comment] 2024-11-22 18:13
> It shouldn't be possible to conflict on the solid_queue_jobs.id key in the solid_queue_jobs table on INSERT there, but this is a different table. Nothing prevents two concurrent INSERT queries to solid_queue_ready_executions with the same job_id to happen.

I had thought ready is called after create and on release of an executing job. When would two processes be trying to insert the same value for job_id? Nothing will be executing to release till the job is initially creating, so a conflict cannot occur there. And shouldn't jobs only be picked up by one instance at a time, so two instances cannot ready the same job?

Would doing the following:
```rb
    def ready
       ReadyExecution.create!(job_id: id)
    rescue ActiveRecord::RecordNotUnique
       ReadyExecution.find_by_job_id(id)
    end
```
be a reasonable solution though? It is pretty much the same as `create_and_find_by` without the new transaction wrapper.

**Comment by rosa** [comment] 2024-11-22 19:16
> I had thought ready is called after create and on release of an executing job. When would two processes be trying to insert the same value for job_id?

For example, if you are using Mission Control Jobs and manually dispatching a blocked job, and it happens simultaneously as the job is being finally unblocked by the normal process. Both will try to move the execution from blocked to ready. 

About your proposed solution, I think it might work, but first I prefer to have it proven that this is actually a problem and that the code needs changing.

**Comment by leondmello** [comment] 2024-11-22 21:35
[Created a reproduction with this repository](https://github.com/leondmello/solid-queue-issue-421)

```ruby
solid-queue-issue421(dev)> Animal.count
  Animal Count (1.3ms)  SELECT COUNT(*) FROM "animals"
=> 0
solid-queue-issue421(dev)> SolidQueue::Job.count
  SolidQueue::Job Count (2.0ms)  SELECT COUNT(*) FROM "solid_queue_jobs"
=> 0
solid-queue-issue421(dev)> Animal.create! name: 'Lion'
  TRANSACTION (0.4ms)  BEGIN
  Animal Create (1.4ms)  INSERT INTO "animals" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "Lion"], ["created_at", "2024-11-22 21:31:28.587939"], ["updated_at", "2024-11-22 21:31:28.587939"]]
  TRANSACTION (0.5ms)  BEGIN
  SolidQueue::Job Create (1.3ms)  INSERT INTO "solid_queue_jobs" ("queue_name", "class_name", "arguments", "priority", "active_job_id", "scheduled_at", "finished_at", "concurrency_key", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["queue_name", "default"], ["class_name", "TameJob"], ["arguments", "{\"job_class\":\"TameJob\",\"job_id\":\"315a12e5-e9c3-4a8f-9753-5f28a2ed3d8f\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2024-11-22T21:31:28.593965000Z\",\"scheduled_at\":\"2024-11-22T21:31:28.593072000Z\"}"], ["priority", 0], ["active_job_id", "315a12e5-e9c3-4a8f-9753-5f28a2ed3d8f"], ["scheduled_at", "2024-11-22 21:31:28.593072"], ["finished_at", nil], ["concurrency_key", "[FILTERED]"], ["created_at", "2024-11-22 21:31:28.608062"], ["updated_at", "2024-11-22 21:31:28.608062"]]
  TRANSACTION (1.2ms)  SAVEPOINT active_record_1
  SolidQueue::Job Load (2.8ms)  SELECT "solid_queue_jobs".* FROM "solid_queue_jobs" WHERE "solid_queue_jobs"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
  SolidQueue::ReadyExecution Create (1.7ms)  INSERT INTO "solid_queue_ready_executions" ("job_id", "queue_name", "priority", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["job_id", 5], ["queue_name", "default"], ["priority", 0], ["created_at", "2024-11-22 21:31:28.632862"]]
  TRANSACTION (0.3ms)  RELEASE SAVEPOINT active_record_1
  TRANSACTION (1.3ms)  COMMIT
Enqueued TameJob (Job ID: 315a12e5-e9c3-4a8f-9753-5f28a2ed3d8f) to SolidQueue(default)
↳ app/models/animal.rb:5:in `domesticate'
  TRANSACTION (0.5ms)  ROLLBACK
=> #<Animal:0x0000000106af3550 id: nil, name: "Lion", created_at: "2024-11-22 21:31:28.587939000 +0000", updated_at: "2024-11-22 21:31:28.587939000 +0000">
solid-queue-issue421(dev)> Animal.count
  Animal Count (1.4ms)  SELECT COUNT(*) FROM "animals"
=> 0
solid-queue-issue421(dev)> SolidQueue::Job.count
  SolidQueue::Job Count (1.9ms)  SELECT COUNT(*) FROM "solid_queue_jobs"
=> 1
```

**Comment by leondmello** [comment] 2024-11-22 21:39
Explicitly [set this in the application job](https://github.com/leondmello/solid-queue-issue-421/blob/c059fe4ba6921e19560f184b0ae5102136f65a65/app/jobs/application_job.rb#L7)

`self.enqueue_after_transaction_commit = :never`

**Comment by rosa** [comment] 2024-11-22 21:52
Aha, thanks a lot for creating that. The reason this is happening is that [you're explicitly using a different connection for Solid Queue](https://github.com/leondmello/solid-queue-issue-421/blob/c059fe4ba6921e19560f184b0ae5102136f65a65/config/application.rb#L20), as [described in the README](https://github.com/rails/solid_queue?tab=readme-ov-file#jobs-and-transactional-integrity) as an alternative way to not have this transactional behaviour with jobs:  

<img width="929" alt="Screenshot 2024-11-22 at 22 48 13" src="https://github.com/user-attachments/assets/c1a6f7b3-eeda-4ebc-a930-48e29f9136b4">

If I do this change in your repo, to ensure the same connection pool is used by `SolidQueue::Record` and `ApplicationRecord`: 

```diff
diff --git a/config/application.rb b/config/application.rb
index 5043b5e..6f3ff6b 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -17,7 +17,7 @@ class Application < Rails::Application
     config.autoload_lib(ignore: %w[assets tasks])

     config.active_job.queue_adapter = :solid_queue
-    config.solid_queue.connects_to = { database: { writing: :primary, reading: :primary } }
+    # config.solid_queue.connects_to = { database: { writing: :primary, reading: :primary } }

     # Configuration for the application, engines, and railties goes here.
     #
```

The behaviour is what you expect and what's documented: 

```ruby
Loading development environment (Rails 7.2.2)
>> SolidQueue::Job.count
  SolidQueue::Job Count (2.5ms)  SELECT COUNT(*) FROM "solid_queue_jobs"
=> 0
>> Animal.count
  Animal Count (0.6ms)  SELECT COUNT(*) FROM "animals"
=> 0
>> Animal.create! name: 'Lion'
  TRANSACTION (0.5ms)  BEGIN
  Animal Create (2.8ms)  INSERT INTO "animals" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "Lion"], ["created_at", "2024-11-22 21:51:01.131628"], ["updated_at", "2024-11-22 21:51:01.131628"]]
  SolidQueue::Job Create (0.8ms)  INSERT INTO "solid_queue_jobs" ("queue_name", "class_name", "arguments", "priority", "active_job_id", "scheduled_at", "finished_at", "concurrency_key", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["queue_name", "default"], ["class_name", "TameJob"], ["arguments", "{\"job_class\":\"TameJob\",\"job_id\":\"ed7f2a0a-13fc-4877-8d32-0e8d5f374e2b\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2024-11-22T21:51:01.146363000Z\",\"scheduled_at\":\"2024-11-22T21:51:01.145177000Z\"}"], ["priority", 0], ["active_job_id", "ed7f2a0a-13fc-4877-8d32-0e8d5f374e2b"], ["scheduled_at", "2024-11-22 21:51:01.145177"], ["finished_at", nil], ["concurrency_key", "[FILTERED]"], ["created_at", "2024-11-22 21:51:01.154060"], ["updated_at", "2024-11-22 21:51:01.154060"]]
  TRANSACTION (0.2ms)  SAVEPOINT active_record_1
  SolidQueue::Job Load (0.5ms)  SELECT "solid_queue_jobs".* FROM "solid_queue_jobs" WHERE "solid_queue_jobs"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SolidQueue::ReadyExecution Create (3.3ms)  INSERT INTO "solid_queue_ready_executions" ("job_id", "queue_name", "priority", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["job_id", 1], ["queue_name", "default"], ["priority", 0], ["created_at", "2024-11-22 21:51:01.191264"]]
  TRANSACTION (0.2ms)  RELEASE SAVEPOINT active_record_1
Enqueued TameJob (Job ID: ed7f2a0a-13fc-4877-8d32-0e8d5f374e2b) to SolidQueue(default)
↳ app/models/animal.rb:5:in `domesticate'
  TRANSACTION (0.2ms)  ROLLBACK
=> #<Animal:0x000000012d197cf0 id: nil, name: "Lion", created_at: "2024-11-22 21:51:01.131628000 +0000", updated_at: "2024-11-22 21:51:01.131628000 +0000">
>> Animal.count
  Animal Count (0.7ms)  SELECT COUNT(*) FROM "animals"
=> 0
>> SolidQueue::Job.count
  SolidQueue::Job Count (1.0ms)  SELECT COUNT(*) FROM "solid_queue_jobs"
=> 0
```

**Closed** 2024-11-22 21:52 UTC

**Comment by leondmello** [comment] 2024-11-22 22:02
So, in our actual app, we have a replica configuration for reading for the application models

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :primary_replica }
```

And nothing in the application configuration.
Will this ensure that solid queue will use the same connection as the connection used to save the model

**Comment by rosa** [comment] 2024-11-22 22:09
Yes, I think that should work fine.

**Comment by leondmello** [comment] 2024-11-22 22:10
Thanks for looking into this, appreciate it !
Have a good weekend !
