### ISSUE TITLE
Question: How do I start specific workers only?

### ISSUE THREAD

**Issue by harry-herskowitz** [rails/solid_queue#295] opened 2024-08-23 14:39 UTC
I am trying to split queues into different workers that I can turn on and off easily, something like this:

Procfile:
```
worker_couchbase: QUEUE=couchbase bundle exec rake solid_queue:start
worker_scheduler: QUEUE=scheduler bundle exec rake solid_queue:start
```

Config File:
 ```
 workers:
    - queues: 'couchbase'
      threads: 3
      processes: 1
      polling_interval: 0.1
    - queues: 'scheduler'
      threads: 3
      processes: 1
      polling_interval: 0.1
```
What's the proper syntax for starting just one specific worker?

**Comment by rosa** [comment] 2024-08-23 15:46
Hey @harry-herskowitz! With the current configuration, just running `solid_queue:start, the workers will start each one in its own process, so you can terminate them individually. 

If you want to have two different supervisors, each one supervising a single worker, then you'd need to have two config files, one for each worker, and set the config file via `SOLID_QUEUE_CONFIG`. I'm planning to build a proper CLI and add this as an option but in the meantime that'd be the way. Something like: 
```
SOLID_QUEUE_CONFIG=config/solid_queue/couchbase.yml bundle exec rake solid_queue:start
```
And then `config/solid_queue/couchbase.yml` would look like: 
```yml
workers:
   - queues: 'couchbase'
     threads: 3
     processes: 1
     polling_interval: 0.1
```

**Comment by harry-herskowitz** [comment] 2024-08-23 16:16
So it seems to be ignoring my config and running all queues anyway:
`SolidQueue-0.3.3 Started Worker (37.6ms)  pid: 11, hostname: "e1abb1c8-758d-4c8c-b5d7-3227972dd01f", polling_interval: 0.1, queues: "*", thread_pool_size: 3`

**Comment by rosa** [comment] 2024-08-23 16:20
Huh, that's quite strange! It seems as if it was using the default configuration because it can't find yours. Where is your configuration file located?

**Comment by harry-herskowitz** [comment] 2024-08-23 16:25
`config/solid_queue.yml`

**Comment by rosa** [comment] 2024-08-23 16:35
Hmm... so strange. It should work and I can't reproduce this. I copied [your configuration](https://github.com/rails/solid_queue/issues/295#issuecomment-2307401586) and started solid queue and it correctly starts a single worker for the `"scheduler"` queue 😕 

Is it possible the `config/solid_queue.yml` file is stale in the place where you're starting Solid Queue? Are you setting `SOLID_QUEUE_CONFIG` to another value?

**Comment by harry-herskowitz** [comment] 2024-08-23 16:56
hmm, so I have 2 "review" apps that share a db and run solid queue. I don't see how the configs would cross though, unless that gets loaded into the db?

**Comment by rosa** [comment] 2024-08-23 17:00
No, the configuration doesn't get loaded into the DB. However, running two different apps with the same Solid Queue DB might cause some problems with jobs from one app running in the other. In any case, not related to the problem here, which is that Solid Queue seems to be ignoring your config file 😕 Have you checked that the file is the right one for the app you're testing this with, and that `SOLID_QUEUE_CONFIG` is not pointing to a different config?

**Comment by harry-herskowitz** [comment] 2024-08-23 17:27
Okay, so I ran the installer fresh to get the original config file and configured it from scratch. Now it's working. Not sure why since the file was identical but maybe Heroku just wasn't picking up the changes? Anyway, thanks for your help!

**Comment by rosa** [comment] 2024-08-23 17:29
Ohh, glad to hear! So strange it didn't work before 😕 

Going to close this one but let me know if you're still running into trouble 🙏

**Closed by rosa** 2024-08-23 17:29 UTC

**Comment by harry-herskowitz** [comment] 2024-08-23 17:30
Oh I see I think the indentation may have been off
